### PR TITLE
ENSY-99 add github actions workflows

### PR DESCRIPTION
**Pull request by tim-rix**
Add github actions wowrkflow files and paste in the outputs from
mitlib-tf-workloads-ecr (dev/stage/prod) outputs in terraform cloud

Files added
* devbuild.yml
* prod-promote.yml
* stage-build.yml

#### Helpful background context

Adds the output values from the dev/stage/main environments of the mitlib-tf-workloads-ecr 
repo in terraform cloud.  These files perform the automation needed to deploy and update wcd2reshare
changes once a PR has been approved (dev/stage) or a release has been tagged (main).

#### What are the relevant tickets?

[ENSY-99](https://mitlibraries.atalassian.net/browse/ENSY-99)

#### Developer
- [N/A] All new ENV is documented in README
- [N/A] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer
- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Includes new or updated dependencies?
NO

### CODE REVIEW

**Comment by cabutlermit** [comment]
The failed GitHub Action in the checks was due to the fact that you haven't yet deployed the infrastructure resources for mitlib-tf-workloads-wcd2reshare yet (so there is no `wcd2reshare-dev` Lambda function yet to update).

**Comment by adamshire123** [comment]
I can't meaningfully review the code here, I've tagged @cabutlermit for a review as well.

**Comment by cabutlermit** [comment]
@tim-rix how soon can you deploy the core infrastructure from https://github.com/MITLibraries/mitlib-tf-workloads-wcd2reshare into Dev1? That should be done before this code is approved so that we can be sure that the `dev-build.yml` workflow will execute correctly.

**Comment by tim-rix** [comment]
@cabutlermit Infrastructure has been fully deployed to the DEV1 environment.

**Review by cabutlermit — APPROVED** [review]
looks good!

**Pull request merged**
